package org.checkerframework.checker.framework;


import org.checkerframework.checker.returnsrcvr.ReturnsRcvrAnnotatedTypeFactory;
import org.checkerframework.framework.type.AnnotatedTypeMirror;

public interface FrameworkSupport {
	/**
	 * 
	 * @return {@code true} if the method is generated by framework and returns {@code this} 
	 */
	boolean knownToReturnThis(AnnotatedTypeMirror.AnnotatedExecutableType t, ReturnsRcvrAnnotatedTypeFactory typeFactory);
}
