package org.checkerframework.checker.objectconstruction.framework;

import com.sun.source.tree.NewClassTree;
import org.checkerframework.framework.type.AnnotatedTypeMirror;

/** add CalledMethods annotations to code generated by framework */
public interface FrameworkSupport {

  /**
   * Allows for supporting a framework's {@code toBuilder} routine. Typically, the returned Builder
   * setters invoked. So, the framework support can add a {@link
   * org.checkerframework.checker.objectconstruction.qual.CalledMethods} annotation capturing this
   * fact.
   *
   * @param t method named "toBuilder"
   */
  public void handlePossibleToBuilder(AnnotatedTypeMirror.AnnotatedExecutableType t);

  /**
   * For {@code build} methods on {@code Builder} types, the framework support should determine the
   * required properties and add a corresponding {@link
   * org.checkerframework.checker.objectconstruction.qual.CalledMethods} annotation to the receiver.
   *
   * @param t a method that is possibly the {@code build} method for a builder. The only guaranteed
   *     condition is that the enclosing class for the method is itself an inner class.
   */
  public void handlePossibleBuilderBuildMethod(AnnotatedTypeMirror.AnnotatedExecutableType t);

  /**
   * For frameworks to add any necessary @{@link
   * org.checkerframework.checker.objectconstruction.qual.CalledMethods} annotation to a constructor
   * call
   *
   * @param tree AST for the call
   * @param type type of the call expression
   */
  public void handleConstructor(NewClassTree tree, AnnotatedTypeMirror type);
}
